apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns-service
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCq0gQSlME9CBJNwNBhKMM0Sk91FgxjF07eZDQYu2YCuANjdzOID9tkppTF8suw7sgL7Bj08VO38uExtDjsFMM1HcCQJKOkmrRW0ZP/Jql72nRHtm9yi4picHcvZZltckEOxTORt1AvjezYXVnhIkSsKpD7lqlwEJv4imsH2fR4Id/Cv+PNq4ooBZz0feuhn2WUM0lMln0KJYknLp+53H4u0JzSJOT+BKnxN7lO71ESGxGUgXBJoWOgp/4YzaKd3FmuUn3UeqirB3CAA8DBPwgxKZV5GLUn+paIWZu9GF58R8xN0mr7mBv+lLPSm7ZAdU1c3krE1FtElcpkl4WA5RwNLXurdT3aEqh4S8u3mBAlIoubTm5lm0jdELSDiA5HJ2zjcKbJFNcMs6CM+xkxMEfZUxZNgiL9sJFAF/NK+Qgi+0fJzis5RiLUrZEKMO3L6BiVOmkknP52DvBlJX8SkEIMfYn+gXJo2NwEbiPqxCeHmqJw9QbaVl6WhZwX9lJGJUKIJtDjDawAMm5p/4xKLDe07ah+THE3NSgB/bSvvoMiq0tX5HiwoPYegCgMnHxJndx3g5fB+9W9uXeqLBLrV6JajoWgyZQILoccJK6BRGaGqiEs3Iq6u2YG1+LzuKNpopBIl6ho4qyEzMPaPSzT0sSUpSLnE4WBLKbwoUn3SOfkMMrPtfoHTLh/pirQMjsRndBYDNPDaNlkorWRGqWNBcJcMYgnIg==
    AWS_SECRET_ACCESS_KEY: AgBVghvqpCr5T+9iGrqvvhSPgEWg2GwSgQO9/fWh19/AWLcaYKTld1qfA2BMkB26kPiXqwFWn8REuOhdsz1xaFsxn7gNTa2zxhlItpEF1WKjWO16+t7VkQfLz4C7YTt6QeOkHacN3wdrsBBT0DfDAmmSNQQrJ5QQFV8w81L/YOxMj5IzcED62tVEeGJ0s8LO7q0qp/aZZgrRvoNB6H2yqgN+c3LNMem/HmDs/UBwUI/Mt6mqbrARRCZaRzUFjMVuRvoM6brNCDe93CDudLXfpeYD+4lc0GYQkaTBgmyiMN91GQmvusquVpDtv8K0wM9jeE5xMJqEbZBNxOlGLb5nEMMpU4iXfrJFpwSJmeyp3Nx+PXTIvNSnUfPLvNFXIPPoJ792zqKEC9dV8TbK/oLdJ86PGrYA2iDPCOC67ugtAsxsGOXYWEVYex+MOyOLgNfwP8B9aXCLS7OIkL4Vqnta7LcZUzSY9Kxj3/bgmXmZe6Lyu0liIiypnVfxRlXAyUs5Vhq2D1y8DURNinliQJMN12lnnAip/EsYeQ3x6EIjA+NndN8bY4ZQIplN4Yl0RZ9McHvndVp75evhCKtHDjAVH6zycVJGIDguIIM8GxTp6jfln3xblzSO/PiZvZ58vvymgucUf2WYTfqwRKtsXnNRYBpTIMwAxh9XIvdhuPuGksv5vn3HuymAiGJmKMqF4CheXDDQorBRmuqOUclzGdPLB7Pzd/6dOYXeWYmymR71K45AfcyI8PXFWOVg
    SERVICE_PASS: AgCiKFKf1/EUX6I8H8MutS2onO36LcPIZvITwj8/DdU5K+0/aSBJ78Can/17+NaL07okY2NjVnEsGHvoh+ewC93AUnOaMF6xt2yQ2sTuo8utC3WS7H1Ht943h2g8ScfC26dTy7UTLYjB0lzz0kkksHAELSXodIqgo1exU3nj33AnnUwOHcJuhJlaKsQUMTiGwSwD2JClhvzLFdI4QEQxsDq1mrjKErVlgj10p6TG86saRB/GXe1qtGHTYL6y8tjUjGperVwhYNAIm3ZKQgJbShbblg4KAfZn5jFNv7NlcsN1lye3LiMHsrn9JjKwyV1edLNSgfcZ0I2pYeOp4f8qmKe4ERNYtAOcZqlZTohGVNube1lNfNhqxdQ7ul9rch4WKEggl4hnnpNCpbS/fUYUUybpCdxYrU1b1ohanEft2SmzDT6weokitX+6HnLlBSTEQOu5csHC4C4SjLhxNytaqIDP919J9nVDCifiLRWbHSkA5GSlQRRdTGghnekPvFB7ZEx7Fw7gIsibyDYZsgwh8vTXO8eZuHueafTVtHkFrfvjMityPx7e3C/knHBLiwMkhOvgC2G+JjZ0E51qtHxNHFNgPiBLC91XS9GEbmrez7gsNS3z7S4ndY14xXP5Ti/0yZ691lCpbdFNL7V1fx1rhMzzb+pGpxyAwwG5gngwgFsZOwBqHEIOqd7aYscqIwWu1LJqYNOL3fwhAbWqieYpMJFFF55NwhkbSJ5v6BiOBUSstc4U4FVoaTtCqiWo
    SERVICE_USER: AgAp0qTJdbxA4mRquxeC5BhD6VIHbFRpJmeTkR8Xnsd35XMDFiyKPP8EEP1X+KjCDZ0VYlqdzJReIErbsfYSjFefBFTB3PsFAFBw3+qOF6S0noWlnwZjCpUv2n+FlFyVyqWBpD+g9BgNDHH/hITS5IRVn3QQryzMr+emGRNayaiJOD37RM3K6GjDY/Ay2dAMcxMHHQJeAG+UYG+QdUKETbj2MbWqK0Eg6tGxvgz31nPop62zLjesuuN/RHSqkWlM1ZHUPdR/8xFKH0PsrY5KKXFVtt+tbrdRMlbu8SC8w5hIhIlE1sb435eRDaW4Toifb53EC4VHuelIDjPb0f64iTWkE8fsT/RdhUdSt+XqdVawOj8agOBcQqmjfInFyqt3SarnuGpi8DCwNxU8Mmqmwv4hAtQQ8AHOGyc87FLVvquREROVjZ6FXs34m1WJA1W/7oU7LTWU0ZOIMrnDiNmH4izaXkpz3iGWgOO1X9XiHBIlB5gcBWQ0Y9Yr0unBiua0mj8OjgIb/6z7li7TIJZBmf6LOMItHDu1OsA40jRTB62XF0rm015rmdKBO7RpGFh0VqBZKhnW5aICJFliiJMPxOg7xWOZJXCW9DOVoMHyr1e/a/oMUvScoVjQllkF3uUQGGe7O5zANw9G7Q3IfOBvnWtNNV/lk8NE8PpZd37JCe7HZWtJl/WKDmbXIOW+C5tAhhKpCwJgWw==
  template:
    metadata:
      creationTimestamp: null
      name: ddns-service
      namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns-service
  labels:
    app: ddns-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddns-service
  template:
    metadata:
      labels:
        app: ddns-service
    spec:
      containers:
      - name: nginx
        image: ghcr.io/jamesgawn/ddns-service:0.0.31 # {"$imagepolicy": "default:ddns-service"}
        env:
        - name: AWS_DEFAULT_REGION
          value: eu-west-2
        envFrom:
        - secretRef:
            name: ddns-service
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ddns-service
spec:
  selector:
    app: ddns-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: ddns-service
spec:
  image: ghcr.io/jamesgawn/ddns-service
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: ddns-service
spec:
  imageRepositoryRef:
    name: ddns-service
  policy:
    semver:
      range: x.x.x
