---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/jamesgawn/flux-home
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgCZAORHtum8/QNyPhhWgcI17MMtGKUUnhGmedm/MpPX/4spZx37+4UR568UsHHKwGAuaZJtwfpZoKHAtZtZ7GeuaYuXumVf0ihiPuZPwdCY3tRFmFKOvUgieQ3Es5B869gPHEebJljmUctBVMYji5kdoSVzh3bvWNL4Ql092w0e//IpX0rK4xtzVO7CvpdbvFGgQG0gwvA+m0K79wnjX9MnDYJHeOsAXViRAxBSCFmIpN5DTBZG4IzUnoha/3Ea1FX8/Jp3qJ8iNF/8QCgDAFsax8PkhY6wbpujHef4oJ7XGO5Fq5Og4TtLmNECxuiLiyLk/7eOZCis6qL7qikPoPqgKcDhv0t8/4Ir/kQKwKrsNAAulOzeSQq407kzDRNnVrUJb3XgUeYapty/Oka80j7Sz4rEwwiMBsZDrkS1rwC5RKxAiVqCuqZcRi7eBYSt3+/XVrkWoiJ4/x3/g+JrGeNAHRcB1MKl/s2Kym2i5+o79eOg7tqrmJb53cE3LAMYsJoQU1rFsga39C+Oa9hTmLeXucisKZMeay1Q8rm8+JMKa9p3Z87sPvr62kycUt9HKaFVJtmmTb97OZppk/Ng4gO71XsV29+fAV8TG8jCcYZcaC5iQobYXssub8KjblKzod5JqqZWDvA4KD78gBcXWBC61aVWgtwpexql/G9J9o5bZPUWLPJNGAtCl2o/sk66q3bxImyGZjJwkP4uye6o+wG4wIaWAWv7dybhtXSLWeVlDh588bi213njbTuzJC/m2i/pVfYfXIIXWAuNiO3JGYTdMsg16W4tWiBTNcA06J0F
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: general
  secretRef:
    name: slack-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: slack-alerts
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: ImageUpdateAutomation
      name: '*'
    - kind: ImagePolicy
      name: '*'
    - kind: GitRepository
      name: '*'
