apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prod-route53-credentials-secret
  namespace: cert-manager
spec:
  encryptedData:
    home-secret-key: AgAsqsPumUCUBpoOj400udoE0KX/31J7VRe5UwnhjDtolc+zM58NT/1cyTq1TPw2gItbObVM071l15LnDDPLmKwOXl+5rd4szAjGK1HxRmIjdG/em6MhT4mxII+tT+oVP/pkHPPpn2kxFZkO+CEKXkFCVFItrQxVF5jRP8t0OQWic0M+NrXqtI0GJg/bbCx5NZ22DksxY+Gkp8IW9Hwit3pOXunVFXqwnUwXuu2BH11sKs/Txf5ZrZC41GAmch7lBIt4We/1LjjIRaqXGtyLP30MXJrJTSkPRkQB3T7zT3TAhhngXYzClaWq8NRl9j4M3Jk/hVo7+FK8RX1WNFZgJ/6C7V5wnrYWn7r5wkvFKYe1iy0zQyhsJGFCT2FgECzxRlz6BCpqrZ17okvS2HglS06z5xZoijWRzJ7uUQFIjB8eUSnxi7dLYxdqOhv1QJvmjmhF9kjwDgucpCwxM9gmtL3XnA17G71JJX2ybRsCQkRgXt0ROU+x+GqOOvxXIaQP6BdouTDjrxXAEMHmBpwiQ+WOV7m7Alva1+R40xAyQ1SZBnvdt1BY3KvzsXtFVl2vztoszTlMDG5cQGle9NOdjYo4HyribF0B3lsmM2k/sxwvEXh1siqNlNNQNpQn3eE/gs1KYnsiSrlt41y6knbRACBXahDyc0/QLYbEw9uPefv5MflzrQXu64DJFDh3wqxm9/flcf03JERXZdSgH9dFl30OMBV3IYieKuqXqmtm4JcPk+P6voSg9Z0cqBg60AiYYD6o7BVVf5p2yg==
  template:
    metadata:
      creationTimestamp: null
      name: prod-route53-credentials
      namespace: cert-manager

