apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: gohelloworld
  namespace: flux-system
spec:
  image: ghcr.io/jamesgawn/gohelloworld
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: gohelloworld-a
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gohelloworld
  policy:
    semver:
      range: 1.x.x
