---
apiVersion: v1
kind: Namespace
metadata:
  name: datadog
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: datadog
spec:
  interval: 1h0m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 1h0m0s
  url: https://helm.datadoghq.com
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog
  namespace: datadog
spec:
  encryptedData:
    api-key: AgAEi02Ds0Zr1SX6VAHAn13fP8U2NKF78F0diMw836anBJL2WGHrp9P+k0EkGFaO7quCy1UPZO4Hbk1TpRMuCX8mkCc3B5lf+nwtZ3TF3RDYyBs6V4T9Jdv7eaemqWhQfMzqTFUH4QDflPA/0urhvqpq7hZKhRmdAUEQ8OLsCelNddHosHNhDkccOvYNzTuV/WRpXmnQuysZRWC5g1TjKfYDY5V2E7Kdtw6CIplDi/AL09cQbmNjSyYLTG9U/7NQMLx2R7/DsJ0BdrOktx+mc0xjHKt//vUxdubBlVzmaUu81wFBuz7woUiwpxwNdwszJgKLJKSrMuFO3M7MzhQoigvPr71v25Wg3Y0viqq4QprBjZSCqGdOiQxqMvmyXp/a6EopIgj1Yu3BnWJ8p5la7H0oKHSNuxwEZCRI/Y7se3Km04Dvrz5qJx9QfYkhElaMynHo6MpaMKH5htjg3V4eXTLCbEkI/ZbSvJ9UECn6b5Tk7SwgojtjIANhflG5GV2UEdzOVEz6bLk1Wm1WZkfPLGMzhxi4V6d+4G3zUBOHqWgvcsjoOVo+dnaUMrYolM/fwDMt6mzlT3shzsoNoVD85OIqNq7B7f3YjetvRRPHphriWM1BB+ZNBtQhiuv5zbixuJwaVxBRssSUs21b8IQ91/mxupeWjI3AgTrBlRWmQdWyWEuQrXO+En7ITWdHA23NvGMFMl4Kw51e+JyDXMG+ncIKV7PNT04Dwl8EleIMNdAqAg==
  template:
    metadata:
      creationTimestamp: null
      name: datadog
      namespace: datadog
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  chart:
    spec:
      chart: datadog
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: datadog
  interval: 1h0m0s
  values:
    datadog:
      site: "datadoghq.eu"
      apiKeyExistingSecret: datadog
      logs:
        enabled: true
        containerCollectAll: true
---
