---
apiVersion: v1
kind: Namespace
metadata:
  name: datadog
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: datadog
spec:
  interval: 1h0m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 1h0m0s
  url: https://helm.datadoghq.com
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog
  namespace: datadog
spec:
  encryptedData:
    apiKey: AgCZYRrKC9ImiRjIdGu78/qpdnLxI2F9A+zLFeyQDTomxy3ulv3wo0NpZ6NvDeJWXHOHATi1HA6uc8KsSoRMpCXU1K0eHya68Q34rYiImrCrhrrVGG9siaZo6tOGC0DeoqA1NZFYfBrK2Alnl4gmLhAPgsBvsEyPrZdBOyYBvonYJMLBBBBss9ivnmk0VQ0ycXpm+XfCRbJtTH+uj+/IThM6ybwv8q2v60QSxbYmtJ2+vbMAqbzeJLq9ewya1db6SEJ55j0XXY56wnYtp0zqbEaVe7TOEJulNfGTuSGkfHOzM5Gefo3Slv0cTcXSjp0WUHIdma6jbjHXAJAz7eSPjp+e8cNt7IVEYwJhixZG+cNLcCMRvtRT+vX2M1Oy3hP5BL41lJ5oiB5GFqvcKuN9WaqGoWoh7y10yYbdjqQ42h15FX9llHIyQhZWUt/Dc02fne3bI5QP2K/FJ6XZNATVtvh1XwnmYaa6Wmd+rV4jBsKqXe/ROA8jfaRzpYSr7gNyg2XVTDfHrcXI2hmirBJVp8KRgnW5/FGxjqMjzTpyxBMPVAAJADQyqTBKSw2S4mPzqMAGytUezbGrHsBPLRhjA5Yedz8oQaSfg5wDU5/s3eb16MTDFxmoarJanXK4gkAi+ga2yK84odJtY9yAnkdN6giYO1VXquqt5u1DlghQRcIdEU2Zqs1vQUKs/tw9MuRW9Vg6phxWVCgG+SAneJAw02h2yTTLMbLJspxTECyj2xcksg==
  template:
    metadata:
      creationTimestamp: null
      name: datadog
      namespace: datadog
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: datadog
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: datadog
  interval: 1h0m0s
  values:
    datadog:
      site: "datadoghq.eu"
      apiKeyExistingSecret:
        name: datadog
        key: apiKey
      logs:
        enabled: true
        containerCollectAll: true
---
