apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: promstack
  namespace: monitoring
spec:
  interval: 1h0m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promstack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: "kube-prometheus-stack"
      version: '13.4.x'
      sourceRef:
        kind: HelmRepository
        name: promstack
        namespace: monitoring
  interval: 1h0m0s
  values:
    kubeStateMetrics:
      enabled: false
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kube
  namespace: monitoring
spec:
  interval: 1h0m0s
  url: https://kubernetes.github.io/kube-state-metrics
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  chart:
    spec:
      chart: "kube-state-metrics"
      version: '2.11.x'
      sourceRef:
        kind: HelmRepository
        name: kube
        namespace: monitoring
  interval: 1h0m0s
  values:
    image:
      repository: gcr.io/k8s-staging-kube-state-metrics/kube-state-metrics
