---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: default
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: image-update-creds
  url: ssh://git@github.com/jamesgawn/flux-home
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-update-creds
  namespace: default
spec:
  encryptedData:
    identity: AgBQkz6zFe4DGo0MVHpP0xoKHh+atsKDFH3q7LzYhRKWtdbaxhYKZBNGPdNJ1ZHIj3Ds7bketEoEg0rkDWE4RsRWCh2HlDXvdtPv122z+stPXimTqHKQFtEDQaLOltc++JgCWiq9WZFYyiVqMURNzzITMm8iCGkSrm9mQoh60iKjIvO7qq9N6FtuGYNAyrHzEEQf+jgi6fng2jJ5TChRR/91XYmWEW9hogGOWhHicIazsMIUxd8XFHkoLSOpTgVEnCgcIisKSyhutitkbfmkLbU61baHIM1anIydmBgwPbfs4DoiW2fXw+8wVTNpxGyyHAMlbXCXfndmGVU5KElxXj9lHSoRlXufk/fQnsd5siNuikx9iHIc/qR9GeRM+KJEztviA76oh+ZNq0pop8azkAbB6SFHFu4+rhVRd4vcyGYz/Cb9yV0V95p0flbzM7NwrL1tOnD2R2jwKTo3/lFUlo5v9VdMk4tJ+uSXhv8rgQ9mC7WjJvOOnpwcUnT83E9692Ica0fBx/xcY4NK5FU48jJj5GrEfhVP/Y66z9vImr9/YbCIPS+g9WAm9w5udcPku7bevydtMR6qxwsN+ivVCGnr7mmOXCcQzumUqe524NzQB7kaPEVjhJURUmjrpp9B2EeVREhZYqZ0JnWLOw20LD2tYebF1UMPWnlPB0INUiosX+Izn6fG2P1RhWhJ1f4r1xmY/ewn2X1zfcUfk/fFeALqfOBQbbL0ZplwmSeKouTE0ErQGzH6hJmYAaPeQA/d56AU/2jBMcsKnt+fsDEx+QHjx7pwvxwJ4Jy3OQtFVdaotsyXtpryFUyap6cOvhxRAjqKQhw9XHHJf5MpUULCUpz69nfcGRW8KmF0lPMsH7SrVbQVVw35QXeOYq8gAiP04cG+fr2IpHu5Eph1Iz6PC6cmyPOCRJyXXZFdX6YojnlXNkiVtMlNYaUwBJbwO1hkj1vJ5kI0JKcxn7f5240168107ImkxRdepz8FqFCo5+vkibeDjV0PrMNoprTTYuPCsTSuyw==
    identity.pub: AgCIW35DZasUtdOky/a3W+gYZS5BxQ9lI2NknOmD35TcjBHE4ARN6KxuJhgt4sp1ZItN0Wa6RTNfXE39ztdXg8aZwUg9/2ENXHxwGZiZd5mAe2/Q/weL22LerfhUh1yfeywo4EGYbwGYygPM4iaPhs8jvh96ZoHPoW2n9k0uZPU9c/cfhQVMTzr+rWHAizhFqf0oAyIrc2ZjQfbfbQNJ89wLI5uYBB9D+3P2nBXEeXHqJ8SPjR6Ce/jOQ9S4HwhPLAlHOPL/3kee7SWJbtuvKGqSKnibpbEJbaq0PNIgN8uu4aRLXZWp0gJlpHWJ87LJzo+a4jnsOA5XEH1YiOWyCJy2C67+DAV6Fdb8Ab/ybj/Rbhrh6vXXOd+CZLzCC6DjjwOyeel0saSxzGn+qwS63Kf9UgQVSkl7RuRUqc5jL1/ttJLX9dLOHa5dcqpKR68PGJsqrKpe+uvYf9Xux4nZl6cn66mg6u7Q5/pvu0CrGh2vj86CGhZn/cSuw5r/3SvSkPp6N6AwvcfBUbfBpI8yG70bjQx8bGG6MHrmv9QamMM2D2x8+2EvePoznjW3H1jQ79PTl1jgJOT0ytQPtjFb9EVpNeUkJ3gM3Rfkrl9gMt6oCyhODvYg1ox+cxhLKEP3dfrBk1KvDCW5VJyVUYMpPZlLIsJhg8TRz1rW1nbzshWtmV+oNvuRCsp1GAxeAYxFAiUrLEtGRNxl/nt46FAamNv41DlPVOb+vlL7skUhAmf1zedIgaVGrK8MsjzpE0MVYiVm87s=
    known_hosts: AgCkj+gbBi7QgjZLBF32KJ8oO04kv/sgAdXp9EAi9Ll0vB61B9I8BuUWlAdkhn2QAUhT6Z7w+PZBqp/vcAtzJ7jXTS1XOmB8jw3I0TPKvWAi4NGKAVfqWbD6Q4RXWskfEaHkiXPqmUlvFbFIDWK6hTYIrhTpSWA9OQdywcyxsTT7BpwywCkoDvx7hAGE2BYixEqGZo5SLIYlQ0fQzCDS0lO3aFUVFbvAbqw++ldM7ekMV13ND7M95SjxsEitBCPMt9YdLNgBtDkgnj1c4oQ12dP6oiX7SjmkNcWIqJiYYSd2PUgZ3bmT2pkpPj74Z6WdR/wyhuEgh6Qe0488Y5c6qCDqkz7btldbhzxoQqx+RYy/K+JbrnrYQ7Pc8YRC2tVuspgt7piyVpeTU7HDZz6g/bfsiweNS6FcR+34W/TE6cEapd4otMM5o6weerS4Q+KzL06G4aIBFbxyQj0tPIKQlKDzwDcQbFG/eSnLyqKEq+mz+3Cc89gbJq940hHR5tx4qIvznGkYfYqVJOrhe88XfwyuC2kbsQ8/IM9ldTImjGmpcbYe70lJmHTta2EtnofwxKxZV3eR5I2fQPWIajVM1zItLozQBrwSORl0UeMVhR+0NPM7pltDM0hmG9IdwufnbnCX32LXy07er63AH3kYCPojG8fk0db1pVPEc7v871ccRCoZ6s4tEqsQSQbFxrZUEI8Nb5nD1nkxiDOkUKBdO1VtgqMYCCJPhQImwpe3qmd0NB3E06guD63uml0xh8vcp3DlHMtHh0ElRbt0hFxqgqCb9NGYuU7d+2wsYomtUMwskbmfbu3IkzUjIwrOz8VcBE4Yl4i3Yu3y37FqA+p4MCLk0uX4ia/Ne25GQlUffwZWzRNPT61A2ygzcufGzbwjGy+/zVpz2Xwcz9l155B9ZbaA1WeCjq5xeFLD6VIheSByJl7UGgkL3u7rD5XEvdkDrqQQxb3kQMjLHypCGqHXTsEndBcf0zMMv4HP44bmjjGGRpxHSvfiWBHVkxfcCAVfcXHfzXVSwfsQZ7Zlce42X8NTJx96nRONFOmpcyxyRzVI9/Erx9GFHFEzbzT0+/WCadW2/hIaGzw1ue9NFhYkiDn75pdBGhzOy346ngvuh0o/R2kWOYydXk0nlVMPxftvP8q8WTdmhtMjMVkuEkK9Ah8YrxHmw2xSRVqqL3MDzjD4Mzj3FCjimOZo2DQCEqcfUZQo1nvn8ehwwA==
  template:
    metadata:
      creationTimestamp: null
      name: image-update-creds
      namespace: default
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: flux-system
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '[ci skip] update image'
  interval: 1m0s
  update:
    setters: {}
