apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns-job
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCymA67Jqdy5FcfVU4is0m9dFLa9O1ufmhGPOp1Iu5CVOW5jNXfpla0ycEkU88E4iTL1glEU0rwJZa9W21BrONBI1THLLXc8WdREqZ2OyY6jCwGveKBkSUJ+TNiDENz3qLd0FNbf0Sjwh8VsnCj3RLrICLSXNyB9EHUYyPPvIjcci90bzdyWw6LafFhayGf0cb0O5xPy9L8xJowX6vvrkUbbLwiiALDPOa7V7IRVwWVxENdrSK/I63FfcciLuzLRr1ROm9Nqv9TSBb3XzANraZjUjIwwuHwokSrFMORyYdOqdIytjb8aEuDXuVVg9iQdpZ6rIEgfTqo/Z97qUGA+t5blxsZ0oB35sbgCAjYIdMtmRf9MhVGAfhNoJosYteqPH6JwW7B0oAa1Rv/EwB1Gex3yF6HL3g3ZDy/mEh7n6SisEfxv5rpVzKaXHMkTpSC2cQw8ZXuD0hnrTfHUWGqlWMcOw+9CAr6gmrkzDnJLF9oKe2CJFJ8/iqpvKsng4wBxpi666j9le743hHkssDIkeUEdzCSM+oqkaXWTa4vIgoKpoOgHNmx/R6jOKOYWbfT/fYmNtmAJpUMnSyrFJUIZQ0TzWRAQGpCdWKuBQ8vl0u+FbmloNIYNgLdJTXhq+UpVXn1fk4L3+Suaj7yAyuhLoGQYi4uO6T1rJlkpa1DLxmHUVxcytrccRaHvC1eKN6EMu2SyxTpoXY0JnjE8C4TIiI=
    AWS_SECRET_ACCESS_KEY: AgDBp3f9Xp3Snrv43RXd790+EVCJmK7iOK6YvPXytaqkkkIIFSoljreKrLN/Mof3CSu6l8PiOHfdSdVbRqrJ5xPFxywONTvyw/1u7PqaUp5qhmJSdZnMGG77zPN0E+GAGmq0EHJaeOAb+m+xun+F9Ukl9nQzpT7jnlhFCdPs0qaKWrDTMX8JBdG79wJ16GSYNLNR6tK1KVAtB7fQe2y8iIyRoQwJv1AQGXWAby0y89F27umy7sv0gWS7Bt9d9mfnxKdifVS87lzLtHyHujeCelEsYIoQjCgPPkSX5oGPsa6uT2HEhf0LLse3jv/j5Qr93J6/NY4Ah6sC94l4/Vb+BIXZDIqDrLYjJ1ARlJrP/PbDpZHhHOvQ1IE6Z6Osgz/l2+0IxGUg0XbZj2sSiutPjy/dccqmu055o26Dl65upbGvOoixWia2knwPJNFzjIJL+JM8Dn0uuIASxjIj0nN+Q88OOmsjcZEL9dEeofgvrdBdo8f4qoR0FsteBcevIDlwEc7incj+PSn9Jd0BaMAkWEewq+pjv3rWSivGJh0UgEzbcDsi9iCSRbDGjmprC9ptn4PZB0vO1QmjK+7PwtIIlmksHLLPkaTV5/QyKylqIb71IEwxLQNn3npzwcZKFpfu5ywqJJ8XdXlmrQxIPCXs0qNQzNiZdvis7/ebiEyNM3knlqAf61zfdfjwcxydnhiAhma58tp9p2OPonhdLQ2V8rEywr+O5E+fnqfDAI/qKdU=
  template:
    metadata:
      creationTimestamp: null
      name: ddns-service
      namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ddns-job
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddns-job
            image: ghcr.io/jamesgawn/ddns-job:1.0.0 # {"$imagepolicy": "default:ddns-job"}
            env:
            - name: AWS_DEFAULT_REGION
              value: eu-west-2
            envFrom:
            - secretRef:
                name: ddns-job
            args:
            - "-z=gawn.dev."
            - "-d=cluster.gawn.dev"
          restartPolicy: OnFailure
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: ddns-job
spec:
  image: ghcr.io/jamesgawn/ddns-job
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: ddns-job
spec:
  imageRepositoryRef:
    name: ddns-job
  policy:
    semver:
      range: x.x.x
