apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns-job
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBPeXYIoymBHI0UUJ7zTsdXGYRfkO3/u6uLz6z/sTsf8if8cButgq0l9VoMN9YEwgRc1/tOeZpGSM0L3+rxRNiQhejcJpW2QZplM/p7J8AWOlXcxB1YpnluYM+YdykL0OXK+g4gJY3dEqruMrlCy5KzCzggLInUjcKChnv/dw8q/hc4UnBOrJgdxIhxA6NCSnEuc3t8gmXObcZtKVvIAQ5gEeJu3jEytZDNMHSO6vLZg9Sgj6FdzehHkXgaPs+BPsegI2TVe7KXSau6SzY8vBtF6t93fgnVtm06yxYqweFmwmn7o25CyVaFUvNxdOrTwXAoTdmgH+7v4sLjPfE6czgBCeZ97K5v2i2HfEzDJaoNk0YLtyywJDJMn6ekDCRvOQvvASkRxqfJjJTriZNWMgSoUeTdXM9AbvUx5LDS4jy06kjeNoV2e/8v2H0zPcui8MuLLEgs7I1Eu64eHGJH1C7WvNEldpwc7boWlFBdlhr3WYsXq7gq7udf/4402toQJt/gB+LgosEH5eUo4dhWyN0ml6/P9gZThRO5NhBOSsV3wiqMkhl3koUkZ2UMP0mzrEa0zpn4sw2HY6DkJYluz7L4s3+VACZAnskK8g5CjLKtWwM+RvlB/UYqdGL/KJge+NW1EZs87Hm8BQkIfICD7yhoYGZ0qbU/Xv+6NMi2JUL2iLMkRp9mz+SnmjYIXS+l4eHjewlwB9WpXkq8u80Xn7bMVAhExQ==
    AWS_SECRET_ACCESS_KEY: AgAW2cjc0FAFO/DIMidP8SLj7sfBH0l6ThZBBgzc/7M2+TWf99w/4naycQQX8uzGkhNIXeP0N+yZLLyDUx5783y1hacK7e7i/63v0sezncCdcrjTTOeI9CVmPTjMg34Z0j12lR8Ixl6TIpyePKrytcfFw0JNIGKy48YV5KZTUU7CgPauMjXfPZPPeWs+QpyjAFq//3J7Xt1kn6xWvrYwC9r4UCdmJBcRgeb6ZgHHSn6Y1/FkjAjHDMVK74TpcHcdknRTxn014gAInqluer0nJFKccaiJrJZ85rDLna3DWS++RHbNxmfjafj+2BtFcphLqADU6lXX/xYkdjdyuYmCphSNxWabZXzT3yENpjZ6mPN0UMMC65VPx8lbzZy0gJR9tynjBTAEvGOe7dntmVa6AgFF6RYUXnvFdcgbSJ3KXcNK218Xap89es3xqmjaD6hdutGXEvKCY8EabZakMlliDqjdDib54RQBGOzaHhjvOYEpOesae4ppMeLaqpVSDe+RfALzD+GEtAqJJwJL5fBSo+nEG/6SgczHPfc7Lq+2jmbB6lCtIvL+ZUyalQdIiwf+hxXYdnwDHkha7qa7HDUHJLtu5GOZsXf18erQCH/V1kEYi/EQN021Vt9VYUZ18faQSeNKCthFEC9j6F/81ZlsGV7rD5rEPMYbWTMinrYYwEDAstHvlAUGIQRxT9olcK9n5N7ZtSZH3oMupmlkjI3SxhglrdYg0hwzd7Li7sUez9lt5SooUY93+AFq
  template:
    metadata:
      creationTimestamp: null
      name: ddns-job
      namespace: default
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-job
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddns-job
            image: ghcr.io/jamesgawn/ddns-job:1.0.0 # {"$imagepolicy": "default:ddns-job"}
            env:
            - name: AWS_DEFAULT_REGION
              value: eu-west-2
            envFrom:
            - secretRef:
                name: ddns-job
            args:
            - "-z=gawn.dev."
            - "-d=cluster.gawn.dev"
          restartPolicy: OnFailure
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: ddns-job
spec:
  image: ghcr.io/jamesgawn/ddns-job
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: ddns-job
spec:
  imageRepositoryRef:
    name: ddns-job
  policy:
    semver:
      range: x.x.x
