apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohelloworld
  labels:
    app: gohelloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gohelloworld
  template:
    metadata:
      labels:
        app: gohelloworld
    spec:
      containers:
      - name: nginx
        image: ghcr.io/jamesgawn/gohelloworld:1.0.0 # {"$imagepolicy": "default:gohelloworld"}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gohelloworld
spec:
  selector:
    app: gohelloworld
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: gohelloworld
spec:
  image: ghcr.io/jamesgawn/gohelloworld
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: gohelloworld
spec:
  imageRepositoryRef:
    name: gohelloworld
  policy:
    semver:
      range: 1.x.x
