---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      version: '1.4.x'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  interval: 1h0m0s
  values:
    installCRDs: true
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials
  namespace: flux-system
spec:
  encryptedData:
    home-secret-key: AgAeKZDq+MMbELN7x6VMl9E6U+JzLj8VxYUj5I7apGqkpQCXLnfx/rjBu4y7YmW/x7qKa0+T2sqCXETHDK0pkowlVfyS7b+z84mVug0a5UkCPR11yWK61EYDN9mRgoa96loH60FC4OiIeWm8pgpgZcSZPxbXJiYtCYyEyRNijtboNCWuEcU8AjCtUTJION0A6w1IUJEmEXvANqfOxE763HDkS6oABitbWc09wAiwnQX7g+8p0JOizKiaPSbWsK6uhw7M5gZL9LW75fUHaSHwCI4/CKXgtJFbUTe48swvSn2RbSifEWzyw3i/H9hE3vUU+TdKBIJ0Vs4LltWkA0ZNwzLuuVKmTI2eYO2lcGvoltxtPJVynZ3e7sx/pXI8jlKFyu8TBjuKQR4uFk5g5Z7RvVYqVczo6RyxSTA/QlgtUjeUdB+jnT+NVrpLOWC1mNyActbAkblenFGY3uOZrt91gKLxjKW74Fbdf0+x07mmKAkClf79tJqMlgFfB2gUDS3XfFdWxR123xadQgXZLGvvXL/mEeKv/mprvbmee9OPCeXMnFdTsn1QfdqDXb1pxHF/2IRVSeJP4hDWgIk2u7z5svDcZE2G1vl1wH3LkKmjI91m6mL5+HTYR87sekuEBBu1TwJWqVBGpPrBBN7RfwlsoBW2pgN+I86BsvvMY1YeDA3+DDrI93M/3YCWm/QoPbo1aMBzCMzAvMtelylgP5HODqTpHR/XMtzC7DNeufOjv7VwMBhgLDqDhas+
  template:
    metadata:
      creationTimestamp: null
      name: prod-route53-credentials
      namespace: flux-system
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-prod
spec:
  acme:
    email: james@gawn.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-issuer-account-key
    solvers:
      - selector: {}
        dns01:
          route53:
            region: eu-central-1
            accessKeyID: AKIA6IH3BM5DGCUWLG6P
            secretAccessKeySecretRef:
              name: prod-route53-credentials
              key: home-secret-key
---
