apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: '1.1.x'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  interval: 1h0m0s
  values:
    installCRDs: true
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns-service
  namespace: default
spec:
  encryptedData:
    home-secret-key: AgBbwuqEgaRIWZiqpjGsgVQ7BdiIYIPbdKFCPuRmCAOoYN/ZnWWloU4t4MyrsbVYa4bF8x12ACzc3hrlpe3mojJ++nmH1oyUU9HiV2+oFVWC/eXWjaImBk8DGIvRzXpl6qWrJqMbiP+jk2dLUK9iQVQ5AFacqRL9UNo/wRjDYIzJLId4H9SEy54YMiCWwTeI6I/lCeVSzL+Xl5xyM82c/GlQ9Cr1V8Ece0ZPVTPnrm/T26XUqRmEYQcvAhN0xsNks4VPr7tDTqvUNZTABnHA8i687BS/9gzSD39AiLHxw2ojLbHpuqmaV774zIY7CzOgH7ziLVkwJKLi5yjO+zhlsWZLtfirpTn7k+Y6mXx4A5dM51hO7CdRhcnmOav8fRHi+RGefmwD/b1UPEa0Gxkezk7kq5XiYgHe4kVZUsy7jtitnZZ7YqYzaLm5Y2dTyBM2sipyUR/bdWfWKXpbs0rfOtz8/u+7XgwjAMDDKZnfzcpMfhHXQTFmAxLtBWZ+rcLIJkiOWZNIhauHSDgYNqatSwDi9TUFzjJEEYdstuT5adzq+o7YGFotG6y6r+bZdt3T2dFjbM55Yzpl08ylu8mPwZ+ASneU50p6/pdBFjD04kPBRDwKiGIwziqaXbYK5AsJMG2yE8fuN4qekvdjBdthTzSA1lq/8cS/9MiIDNT3gA+gxCXxUzDRLi3X5w7YpPnmbrqYLviEkblrXlOZACVR/fsQFf9vQqcWRe2C+ggrWTk=
  template:
    metadata:
      creationTimestamp: null
      name: ddns-service
      namespace: default
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-prod
spec:
  acme:
    email: james@gawn.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-issuer-account-key
    solvers:
      - selector: {}
        dns01:
          route53:
            region: eu-central-1
            accessKeyID: AKIA6IH3BM5DGCUWLG6P
            secretAccessKeySecretRef:
              name: prod-route53-credentials
              key: home-secret-key
