---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      version: '1.4.x'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  interval: 1h0m0s
  values:
    installCRDs: true
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials
  namespace: default
spec:
  encryptedData:
    home-secret-key: AgAnKJIy8AruHSkaXjM5vDnRDUpoNbCgeuJ3l77mp/j5nBGYgBlSuBwb13w+Q5oP7NNa0kkUQZWfWW6//q3nlkCXPbbpqMOir12qgrhRgQaRxmJZzjeYpEjuKeeqRx4guZWD0mF4UDIVm5yi92lXg8K9HXz3J4m9DAjfkwO9We1PC1hkjYMjYL9Y8DNOpbShW4ocdog3zLfn5ZQu59623SnBSc3X3cdi8zdreG9en3Hm0C2l4Dzl0nrewKYdmMUZAZ2JzrfeO+dVNUltg+O6kWyEGbQBI2t7FHLtmPHyNt+zxRtS+16BhnrNeRZRD7UV7AlFqFFgCTj658jI9al2Gam3jOsEBKKmECzORsPLIDhxuVH9TT9kw34PShlroeKRS7wOqVU6COa/JE53YRa2jIsOJfeJ1g9TaMcfHC/8ri81c3urHRyKw7tm6ZaOzRQnuSobE14Zk+P0nBbbkbHaNTOwnVwZT2Cc3QcCL2S8lok01+8pdMDrkIENmoZIO+IAppoYyJfs4NCt3zxgwFPHWlwezu9dVfZaf2XyzIVGLIiGDsUaN6eaWYf3MneOS8U5MiB3ET+hzJv6tU7fhAAy/soEdUtsBoo5B3C31oLxMQJ4kmLxAA4ZONtn3g6wBtAPUxwEFzrLvPCsJEdU7OaD1FndRKnRUskyJmZ0Dwkq9c4hl5zhtqbPToWNsXMVxSiM7d25dtJbsbmMcuN8Pe42PeUObqgruH8b0ZoKGBgRD9JCbD8m2h3wY5Fy
  template:
    metadata:
      creationTimestamp: null
      name: prod-route53-credentials
      namespace: default
#---
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-dns01-prod
#spec:
#  acme:
#    email: james@gawn.uk
#    server: https://acme-v02.api.letsencrypt.org/directory
#    privateKeySecretRef:
#      name: letsencrypt-production-issuer-account-key
#    solvers:
#      - selector: {}
#        dns01:
#          route53:
#            region: eu-central-1
#            accessKeyID: AKIA6IH3BM5DGCUWLG6P
#            secretAccessKeySecretRef:
#              name: prod-route53-credentials
#              key: home-secret-key
